name: Docker Image Deptpro CRON mongo

on:
  push:
    branches: 
      - main
    paths:
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - run: docker build -t mostofa62/deptpro_cron .
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push mostofa62/deptpro_cron
